[package]
name = "kc-flash"
description = "UF2 bootloader detection and flashing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
kc-boards = { version = "0.1.0", path = "../kc-boards" }
thiserror = "2.0.21"
