//! The generated zmk-config files for both boards.

use kc_boards::Board;
use kc_emit::{generate, keymap, EmitError};
use kc_model::behavior::{BehaviorKind, HoldTap, Macro, MacroStep, ModMorph, StickyKey, TapDance};
use kc_model::features::{
    ConditionalLayer, InputProcessor, PointingConfig, PointingOverride, SettingValue,
};
use kc_model::{BehaviorRef, Binding, KeyExpr, Param, Project};
use kc_zmk::Modifier;

fn board(id: &str) -> Board {
    kc_boards::built_in()
        .unwrap()
        .into_iter()
        .find(|b| b.id == id)
        .unwrap()
}

fn kp(key: &str) -> Binding {
    Binding::kp(key.parse::<KeyExpr>().unwrap())
}

fn file(files: &[kc_emit::GeneratedFile], path: &str) -> String {
    files
        .iter()
        .find(|f| f.path == path)
        .unwrap_or_else(|| panic!("no {path}"))
        .contents
        .clone()
}

#[test]
fn a_new_imprint_project_generates_a_complete_config() {
    let imprint = board("cyboard-imprint");
    let project = Project::new("Mine", &imprint);
    let files = generate(&project, &imprint).unwrap();
    let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "config/imprint.keymap",
            "config/imprint.conf",
            "config/west.yml",
            "build.yaml",
            ".github/workflows/build.yml"
        ]
    );

    let keymap = file(&files, "config/imprint.keymap");
    assert!(keymap.starts_with("/* Generated by Keyboard Curator."));
    assert!(keymap.contains("#include <dt-bindings/zmk/keys.h>"));
    assert!(keymap.contains("#include <input/processors.dtsi>"));
    assert!(keymap.contains("#define LAYER_Base 0"));
    // The Imprint has variants, so the keymap names its physical layout.
    assert!(keymap
        .contains("zmk,physical-layout = &physical_layout_imprint_function_row_full_bottom_row;"));
    assert!(keymap.contains("layer_0_Base {"));
    assert!(keymap.contains("display-name = \"Base\";"));
    // 82 bindings, in eight rows that follow the keyboard.
    let rows: Vec<&str> = keymap
        .lines()
        .skip_while(|l| !l.contains("bindings = <"))
        .skip(1)
        .take_while(|l| !l.contains(">;"))
        .collect();
    assert_eq!(rows.len(), 8);
    assert_eq!(
        rows.iter().map(|r| r.matches('&').count()).sum::<usize>(),
        82
    );
    assert!(rows[0].trim_start().starts_with("&kp ESC"));
    assert!(rows[2].contains("&kp Q"));
    // Columns line up: Q sits under N1, both in the second column.
    assert_eq!(rows[1].find("&kp N1"), rows[2].find("&kp Q"));

    let west = file(&files, "config/west.yml");
    assert!(west.contains("url: https://github.com/zmkfirmware/zmk\n      revision: v0.3.0"));
    assert!(west.contains("name: zmk-keyboards"));
    assert!(west.contains("import: config/west.yml"));
    assert!(west.ends_with("  self:\n    path: config\n"));

    let build = file(&files, "build.yaml");
    assert!(build.contains(
        "  - board: assimilator-bt\n    shield: imprint_left\n    snippet: studio-rpc-usb-uart\n    cmake-args: -DCONFIG_ZMK_STUDIO=y\n    artifact-name: imprint_left\n"
    ));
    assert!(build.contains("    shield: imprint_right\n    artifact-name: imprint_right\n"));
    assert!(file(&files, ".github/workflows/build.yml")
        .contains("uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0"));
}

/// A Go60 project using every construct the emitter writes.
fn rich_go60() -> (Project, Board) {
    let go60 = board("moergo-go60");
    let mut p = Project::new("Rich", &go60);
    let base = p.layers[0].id;
    let nav = p.add_layer("Nav").unwrap();
    let magic = p.add_layer("Magic").unwrap();
    p.set_reserved_layers(2).unwrap();

    let hold_tap = p
        .add_behavior(
            "magic",
            "Magic",
            BehaviorKind::HoldTap(HoldTap {
                flavor: kc_model::behavior::Flavor::TapPreferred,
                quick_tap_ms: Some(150),
                hold_trigger_key_positions: vec![6, 7, 8],
                hold_trigger_on_release: true,
                ..HoldTap::new(BehaviorRef::built_in("mo"), BehaviorRef::built_in("kp"))
            }),
        )
        .unwrap();
    p.set_binding(
        base,
        36,
        Binding::user(
            hold_tap,
            vec![Param::Layer(magic), Param::Key(KeyExpr::new("ESC"))],
        ),
    )
    .unwrap();
    let dance = p
        .add_behavior(
            "nav_td",
            "Nav",
            BehaviorKind::TapDance(TapDance {
                tapping_term_ms: 200,
                bindings: vec![Binding::layer("mo", nav), Binding::layer("to", nav)],
            }),
        )
        .unwrap();
    p.set_binding(base, 54, Binding::user(dance, vec![]))
        .unwrap();
    p.add_behavior(
        "bspc_del",
        "Backspace/Delete",
        BehaviorKind::ModMorph(ModMorph {
            normal: kp("BSPC"),
            morphed: kp("DEL"),
            mods: vec![Modifier::LShift, Modifier::RShift],
            keep_mods: vec![Modifier::RShift],
        }),
    )
    .unwrap();
    p.add_behavior(
        "skq",
        "Quick sticky",
        BehaviorKind::StickyKey(StickyKey {
            behavior: BehaviorRef::built_in("kp"),
            release_after_ms: 800,
            quick_release: true,
            lazy: false,
            ignore_modifiers: true,
        }),
    )
    .unwrap();
    p.add_behavior(
        "hello",
        "Hello",
        BehaviorKind::Macro(Macro {
            wait_ms: Some(30),
            tap_ms: None,
            params: 0,
            steps: vec![
                MacroStep::Press(vec![kp("LSHFT")]),
                MacroStep::Tap(vec![kp("H")]),
                MacroStep::Release(vec![kp("LSHFT")]),
                MacroStep::Tap(vec![kp("I")]),
                MacroStep::PauseForRelease,
            ],
        }),
    )
    .unwrap();

    let combo = p.add_combo("Caps Word", vec![40, 43], Binding::new("caps_word", vec![]));
    let combo = p.combo_mut(combo).unwrap();
    combo.timeout_ms = Some(40);
    combo.layers = vec![base];
    p.conditional_layers.push(ConditionalLayer {
        if_layers: vec![nav, magic],
        then_layer: base,
    });
    p.pointing.push(PointingConfig {
        listener: "cirque_lh_listener".into(),
        processors: vec![
            InputProcessor::ToScroll,
            InputProcessor::Scale {
                multiplier: 1,
                divisor: 8,
            },
            InputProcessor::Transform {
                invert_x: false,
                invert_y: true,
                swap_xy: false,
                scroll: true,
            },
        ],
        overrides: vec![PointingOverride {
            layers: vec![nav],
            processors: vec![InputProcessor::TempLayer {
                layer: magic,
                timeout_ms: 500,
            }],
        }],
    });
    p.settings
        .insert("CONFIG_ZMK_SLEEP".into(), SettingValue::Bool(true));
    p.settings.insert(
        "CONFIG_ZMK_IDLE_SLEEP_TIMEOUT".into(),
        SettingValue::Int(900000),
    );
    p.settings.insert(
        "CONFIG_ZMK_KEYBOARD_NAME".into(),
        SettingValue::Text("My \"Go60\"".into()),
    );
    p.raw.conf = "CONFIG_CUSTOM=y".into();
    p.raw.behaviors = "/* custom behaviours */".into();
    p.raw.devicetree = "/* custom devicetree */".into();
    (p, go60)
}

#[test]
fn every_construct_is_written_in_zmk_syntax() {
    let (project, go60) = rich_go60();
    let keymap = keymap(&project, &go60).unwrap();
    let has = |text: &str| assert!(keymap.contains(text), "missing:\n{text}\n\nin:\n{keymap}");

    // The Go60 has one layout, so nothing is chosen.
    assert!(!keymap.contains("zmk,physical-layout"));
    has("#include <dt-bindings/zmk/rgb.h>");
    has("#define LAYER_Base 0\n#define LAYER_Nav 1\n#define LAYER_Magic 2\n");

    has("        magic: magic {\n            compatible = \"zmk,behavior-hold-tap\";\n            #binding-cells = <2>;\n            flavor = \"tap-preferred\";\n            tapping-term-ms = <200>;\n            quick-tap-ms = <150>;\n            hold-trigger-key-positions = <6 7 8>;\n            hold-trigger-on-release;\n            bindings = <&mo>, <&kp>;\n        };");
    has("            compatible = \"zmk,behavior-tap-dance\";\n            #binding-cells = <0>;\n            tapping-term-ms = <200>;\n            bindings = <&mo LAYER_Nav>, <&to LAYER_Nav>;");
    has("            bindings = <&kp BSPC>, <&kp DEL>;\n            mods = <(MOD_LSFT|MOD_RSFT)>;\n            keep-mods = <(MOD_RSFT)>;");
    has("            compatible = \"zmk,behavior-sticky-key\";\n            #binding-cells = <1>;\n            bindings = <&kp>;\n            release-after-ms = <800>;\n            quick-release;\n            ignore-modifiers;");
    has("    macros {\n        hello: hello {\n            compatible = \"zmk,behavior-macro\";\n            #binding-cells = <0>;\n            wait-ms = <30>;\n            bindings\n                = <&macro_press &kp LSHFT>\n                , <&macro_tap &kp H>\n                , <&macro_release &kp LSHFT>\n                , <&macro_tap &kp I>\n                , <&macro_pause_for_release>\n                ;");
    has("        /* custom behaviours */");

    has("    combos {\n        compatible = \"zmk,combos\";\n        combo_caps_word_");
    has("            timeout-ms = <40>;\n            key-positions = <40 43>;\n            bindings = <&caps_word>;\n            layers = <LAYER_Base>;");
    has("        rule_0 {\n            if-layers = <LAYER_Nav LAYER_Magic>;\n            then-layer = <LAYER_Base>;");

    has("&magic LAYER_Magic ESC");
    has("&nav_td");
    has("        reserved_0 {\n            status = \"reserved\";\n        };\n\n        reserved_1 {");
    // Reserved layers come after every real layer.
    assert!(keymap.find("layer_2_Magic").unwrap() < keymap.find("reserved_0").unwrap());

    has("&cirque_lh_listener {\n    input-processors = <&zip_xy_to_scroll_mapper>, <&zip_xy_scaler 1 8>, <&zip_scroll_transform (INPUT_TRANSFORM_Y_INVERT)>;\n    override_0 {\n        layers = <LAYER_Nav>;\n        input-processors = <&zip_temp_layer LAYER_Magic 500>;\n    };\n};");
    assert!(keymap.trim_end().ends_with("/* custom devicetree */"));

    let files = generate(&project, &go60).unwrap();
    assert_eq!(
        file(&files, "config/go60.conf"),
        "# Generated by Keyboard Curator. Change the project, not this file.\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000\nCONFIG_ZMK_KEYBOARD_NAME=\"My \\\"Go60\\\"\"\nCONFIG_ZMK_SLEEP=y\n\nCONFIG_CUSTOM=y\n"
    );
    let build = file(&files, "build.yaml");
    assert!(build.contains("  - board: go60_lh\n    artifact-name: go60_left\n"));
    assert!(!build.contains("shield"));
    assert!(file(&files, "config/west.yml")
        .contains("url: https://github.com/moergo-sc/zmk\n      revision: v26.09"));
}

#[test]
fn the_go60_grid_follows_its_thumb_clusters() {
    let go60 = board("moergo-go60");
    let keymap = keymap(&Project::new("Mine", &go60), &go60).unwrap();
    let rows: Vec<&str> = keymap
        .lines()
        .skip_while(|l| !l.contains("bindings = <"))
        .skip(1)
        .take_while(|l| !l.contains(">;"))
        .collect();
    // Four rows of twelve, the two bottom rows, and the six thumb keys.
    let counts: Vec<usize> = rows.iter().map(|r| r.matches('&').count()).collect();
    assert_eq!(counts, [12, 12, 12, 12, 6, 6]);
    // The bottom row starts under the third column.
    assert_eq!(rows[4].find('&'), rows[3].find("&kp X"));
}

#[test]
fn duplicate_layer_names_fall_back_to_indices() {
    let go60 = board("moergo-go60");
    let mut project = Project::new("Dupes", &go60);
    let first = project.add_layer("Nav").unwrap();
    project.add_layer("Nav").unwrap();
    let base = project.layers[0].id;
    project
        .set_binding(base, 0, Binding::layer("mo", first))
        .unwrap();
    let keymap = keymap(&project, &go60).unwrap();
    assert!(!keymap.contains("#define"));
    assert!(keymap.contains("&mo 1"));
    assert!(keymap.contains("layer_1_Nav") && keymap.contains("layer_2_Nav"));
}

#[test]
fn invalid_projects_are_refused() {
    let imprint = board("cyboard-imprint");
    let mut project = Project::new("Bad", &imprint);
    let base = project.layers[0].id;
    // RGB_STATUS exists only in MoErgo's firmware.
    project
        .set_binding(
            base,
            0,
            Binding::new(
                "rgb_ug",
                vec![Param::Command {
                    name: "RGB_STATUS".into(),
                    args: vec![],
                }],
            ),
        )
        .unwrap();
    let Err(EmitError::Invalid(problems)) = generate(&project, &imprint) else {
        panic!("the project should be refused");
    };
    assert_eq!(problems.len(), 1);
    assert!(problems[0].message.contains("RGB_STATUS"));

    // An unknown keycode is only a warning, so it still generates.
    project
        .set_binding(base, 0, kp("FROM_A_LOCALE_HEADER"))
        .unwrap();
    assert!(generate(&project, &imprint).is_ok());
}

#[test]
fn per_key_lighting_is_written_for_firmware_that_has_it() {
    use kc_model::features::{KeyLight, LockKind, Rgb};

    let go60 = board("moergo-go60");
    let mut project = Project::new("Lit", &go60);
    let base = project.layers[0].id;
    let nav = project.add_layer("Nav").unwrap();
    project.add_layer("Unlit").unwrap();
    {
        let keys = &mut project.lighting_mut(base).unwrap().keys;
        keys[0] = KeyLight::Color(Rgb(255, 128, 0));
        keys[1] = KeyLight::Off;
        keys[2] = KeyLight::Lock {
            lock: LockKind::Caps,
            off: Rgb(0, 0, 0),
            on: Rgb(255, 0, 0),
        };
        keys[3] = KeyLight::Battery {
            percent: 20,
            below: Rgb(255, 0, 0),
            above: Rgb(0, 255, 0),
        };
    }
    project.lighting_mut(nav).unwrap().keys[12] = KeyLight::Color(Rgb(0, 0, 255));
    project.lighting_mut(nav).unwrap().fade_delay = Some(15);

    // The stock firmware has no per-key lighting, so the project is refused.
    assert!(matches!(
        generate(&project, &go60),
        Err(EmitError::Invalid(_))
    ));

    project.firmware = "moergo-zmk-perkey".into();
    let files = generate(&project, &go60).unwrap();
    let keymap = file(&files, "config/go60.keymap");
    let has = |text: &str| assert!(keymap.contains(text), "missing:\n{text}\n\nin:\n{keymap}");
    has("    underglow-layer {\n        compatible = \"zmk,underglow-layer\";\n\n        lighting_0_Base {\n            layer-id = <LAYER_Base>;\n            bindings = <\n                &ug 0xFF8000  &ug 0x000000  &ug_cl 0x000000 0xFF0000  &ug_b2 0xFF0000 0x00FF00  &trans");
    has("        lighting_1_Nav {\n            layer-id = <LAYER_Nav>;\n            fade-delay = <15>;");
    has("&ug 0x0000FF");
    // A layer with nothing of its own gets no node.
    assert!(!keymap.contains("lighting_2_Unlit"));
    // 60 lighting bindings per lit layer: two lit layers, so 120 in all.
    let section =
        &keymap[keymap.find("underglow-layer {").unwrap()..keymap.find("    keymap {").unwrap()];
    assert_eq!(section.matches('&').count(), 120);

    let conf = file(&files, "config/go60.conf");
    assert!(conf.contains("CONFIG_EXPERIMENTAL_RGB_LAYER=y\n"));
    // This firmware cannot start in the per-key effect, so it is not asked to.
    assert!(!conf.contains("EFF_START") && !conf.contains("ON_START"));
    assert!(file(&files, "config/west.yml").contains("url: https://github.com/darknao/zmk"));

    // An unsupported battery threshold is refused.
    project.lighting_mut(base).unwrap().keys[3] = KeyLight::Battery {
        percent: 50,
        below: Rgb(255, 0, 0),
        above: Rgb(0, 255, 0),
    };
    assert!(matches!(
        generate(&project, &go60),
        Err(EmitError::Invalid(_))
    ));
}
