//! Generates `.keymap`, `.conf`, `west.yml` and `build.yaml` from a project.
//!
//! The output is a complete zmk-config repository. It is always written
//! from the project; nothing here reads or edits existing config files.

mod config;
mod keymap;

use kc_boards::board::FirmwareProfile;
use kc_boards::Board;
use kc_model::{validate, FirmwareConfig, Problem, Project, Severity};

pub use keymap::keymap;

/// One file of the generated zmk-config repository.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the repository root.
    pub path: String,
    pub contents: String,
}

#[derive(Debug, thiserror::Error, PartialEq)]
pub enum EmitError {
    /// The project has problems the firmware would reject. Nothing is
    /// generated until they are fixed.
    #[error("the layout has {} problem(s) that must be fixed first", .0.len())]
    Invalid(Vec<Problem>),
    #[error("the board has no firmware profile `{0}`")]
    NoProfile(String),
    #[error("the board has no layout `{0}`")]
    NoLayout(String),
}

/// The first line of every generated file.
const NOTICE: &str =
    "Generated by Keyboard Curator. Change the board or the layout there, not this file.";

fn profile<'a>(
    config: &FirmwareConfig,
    board: &'a Board,
) -> Result<&'a FirmwareProfile, EmitError> {
    board
        .profile(&config.profile)
        .ok_or_else(|| EmitError::NoProfile(config.profile.clone()))
}

/// Every file of the zmk-config repository: the layout `project` built
/// with the board's firmware configuration.
pub fn generate(
    project: &Project,
    board: &Board,
    config: &FirmwareConfig,
) -> Result<Vec<GeneratedFile>, EmitError> {
    let errors: Vec<Problem> = validate(project, board, config)
        .into_iter()
        .filter(|p| p.severity == Severity::Error)
        .collect();
    if !errors.is_empty() {
        return Err(EmitError::Invalid(errors));
    }
    let profile = profile(config, board)?;
    let name = &profile.config_name;
    let file = |path: String, contents: String| GeneratedFile { path, contents };
    let mut files = vec![
        file(
            format!("config/{name}.keymap"),
            keymap(project, board, config)?,
        ),
        file(
            format!("config/{name}.conf"),
            config::conf(project, config, profile),
        ),
        file("config/west.yml".into(), config::west(profile)),
        file("build.yaml".into(), config::build(profile)),
        file(
            ".github/workflows/build.yml".into(),
            config::workflow(profile),
        ),
    ];
    if profile.lighting.as_ref().is_some_and(|l| l.led_map_overlay) {
        for half in &board.halves {
            let chain = half.leds.as_ref().map_or(&[][..], |l| l.chain.as_slice());
            files.push(file(
                format!("config/{}", config::led_overlay_name(profile, half.side)),
                config::led_overlay(chain),
            ));
        }
    }
    Ok(files)
}
