[package]
name = "kc-device"
description = "Finds connected keyboards over USB and recognises their board"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
kc-boards = { version = "0.1.0", path = "../kc-boards" }
kc-model = { version = "0.1.0", path = "../kc-model" }
nusb = "0.2.7"
