[package]
name = "kc-build"
description = "Firmware build back ends"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
kc-boards = { version = "0.1.0", path = "../kc-boards" }
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.10"
serde_json = "1.0.151"
thiserror = "2.0.21"
ureq = { version = "2", features = ["json"] }
zip = "8.6.0"
