#!/usr/bin/env python3
"""Writes THIRD-PARTY.md: the licenses of everything the app carries.

The first part is written by hand below: fonts, firmware code, board data
and layouts taken from other projects, each with its source and license.
The second part is generated from `cargo metadata`: every crate the
workspace depends on, grouped by license.

Usage: ci/third-party.py   (run from anywhere; writes THIRD-PARTY.md at the root)
"""

import collections
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent

HAND_WRITTEN = """# Third-party notices

Keyboard Curator is MIT-licensed (see LICENSE). It carries, and is built
from, work by others. This file lists that work and its terms. The second
section is generated by `ci/third-party.py` from the Cargo dependency
graph; regenerate it after changing dependencies.

## Typefaces

Bundled under `crates/kc-app/assets/fonts`, each with its license file.
All are under the SIL Open Font License 1.1.

| Typeface | Used by |
|---|---|
| Archivo | Bench theme |
| Barlow | Arena theme |
| Bricolage Grotesque | Gallery theme (display) |
| Chakra Petch | Arena theme |
| DM Mono | Bench theme |
| Figtree | Gallery theme |
| IBM Plex Sans | Curator theme |
| JetBrains Mono | Curator theme |

## Firmware code

| What | Source | License |
|---|---|---|
| ZMK v0.3.0 per-key lighting patch series (`firmware/zmk-v0.3.0-per-key-lighting`), built as the `mroboff/zmk` branch the Imprint's per-key lighting firmware uses | darknao's work for MoErgo's ZMK fork (moergo-sc/zmk pull request 36) and upstream ZMK (zmkfirmware/zmk pull request 2752 and the commits it depends on); one patch of ours | MIT, each patch keeping its author |
| ZMK, Zephyr and the vendors' board modules, fetched at build time by the generated west manifest | zmkfirmware/zmk, moergo-sc/zmk, Cyboard-DigitalTailor/zmk-keyboards | MIT (ZMK), Apache-2.0 (Zephyr) |
| RMK, the firmware generated for the Imprint and Go60 RMK builds | rmk-rs/rmk | Apache-2.0 |
| moergo-rmk, the firmware taken from releases for the Go60 and Glove80, and the `rynk` and `moergo-config` crates the app links to talk to it | colonelpanic8/moergo-rmk | MIT |
| imprint-rmk, the fork of moergo-rmk with the Imprint board crate | mroboff/imprint-rmk | MIT |
| ZMK Studio protocol (the messages in `kc-studio`, written by hand after zmk-studio-messages at the revision ZMK v0.3.0 pins) | zmkfirmware/zmk-studio-messages | MIT |

## Board data

Facts about keyboards transcribed from other projects, with the source
named in each board file under `crates/kc-boards/boards`.

| Board | Taken from | License of the source |
|---|---|---|
| Cyboard Imprint | Cyboard-DigitalTailor/zmk-keyboards (physical layout, matrix, pins); the wired Imprint's QMK definition (LED order, unverified) | MIT (zmk-keyboards), GPL-2.0 (QMK; facts only, no code) |
| MoErgo Go60 and Glove80 | moergo-sc/zmk (physical layouts, USB identifiers, bootloader volumes); the community per-key lighting branch (LED chains) | MIT |
| Dygma Defy | Dygmalab/Bazecor (key layout, Focus protocol facts) | GPL-3.0; facts transcribed with attribution, no code copied |

## Layouts

| Layout | Author | Terms |
|---|---|---|
| Factory layouts (`crates/kc-model/templates/*.kcproj`) | Cyboard and MoErgo, from their published keymaps | MIT (the keymaps' repositories) |
| TailorKey for the Imprint (`crates/kc-model/templates/tailorkey-cyboard-imprint.kcproj`, from the TailorKey for RMK file and TailorKey's Glove80 RGB scheme) | Moosy Research, https://sites.google.com/view/tailorkey | Offered with the author's credit and a link; redistribution terms to be confirmed with the author before a release |

## ZMK add-on catalog

`crates/kc-zmk/catalog/addons.toml` names community ZMK modules the app can
add to a build. Each is fetched at build time from its own repository under
its own license, which the catalog entry states; none is bundled.

## Rust crates

Generated from `cargo metadata`. Each crate's full license text is in its
source package on crates.io.

"""


def main():
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--locked"], cwd=ROOT
        )
    )
    members = set(metadata["workspace_members"])
    by_license = collections.defaultdict(set)
    for package in metadata["packages"]:
        if package["id"] in members:
            continue
        by_license[package.get("license") or "see the crate"].add(package["name"])
    lines = [HAND_WRITTEN]
    total = sum(len(names) for names in by_license.values())
    lines.append(f"{total} crates.\n")
    for license_name, names in sorted(by_license.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        lines.append(f"### {license_name}\n")
        lines.append(", ".join(sorted(names)) + "\n")
    (ROOT / "THIRD-PARTY.md").write_text("\n".join(lines))
    print(f"THIRD-PARTY.md: {total} crates under {len(by_license)} license expressions")


if __name__ == "__main__":
    main()
