//! RMK firmware: a layout written as an RMK keymap, and the project that
//! builds it.
//!
//! RMK is configured by a `keyboard.toml`. The half of that file about the
//! hardware is data, in the board definition; this crate adds the keymap
//! and the files around it. Bindings are translated to RMK's key actions,
//! and one RMK has nothing for is reported, never dropped.

pub mod keys;

use kc_boards::board::{FirmwareProfile, RmkFlavor, RmkProfile, Side};
use kc_boards::Board;
use kc_model::{
    BehaviorRef, Binding, KeyExpr, LayerId, Location, Param, Problem, Project, Severity,
};
use kc_zmk::keycodes::{keycodes, UsagePage};
use kc_zmk::Modifier;

/// The first line of every generated file.
const NOTICE: &str =
    "Generated by Keyboard Curator. Change the board or the layout there, not this file.";

/// The UF2 family of an nRF52840 with the Adafruit bootloader, for halves
/// whose board does not name its own.
const NRF52840_FAMILY: u32 = 0xADA5_2840;

fn modifier_name(modifier: Modifier) -> &'static str {
    match modifier {
        Modifier::LCtrl => "LCtrl",
        Modifier::LShift => "LShift",
        Modifier::LAlt => "LAlt",
        Modifier::LGui => "LGui",
        Modifier::RCtrl => "RCtrl",
        Modifier::RShift => "RShift",
        Modifier::RAlt => "RAlt",
        Modifier::RGui => "RGui",
    }
}

/// RMK's name for a key with nothing implied, such as `A` or `LShift`.
fn plain_key(expr: &KeyExpr) -> Option<&'static str> {
    let key = keycodes().get(&expr.key)?;
    (expr.mods.is_empty() && key.implicit_mods.is_empty() && key.page == UsagePage::Keyboard)
        .then(|| keys::name(key.usage))
        .flatten()
}

/// A key press as an RMK action: a bare name, or `WM(key, mods)`.
fn key_action(expr: &KeyExpr) -> Result<String, String> {
    let key = keycodes()
        .get(&expr.key)
        .ok_or_else(|| format!("`{}` is not a key this app knows", expr.key))?;
    let mods: Vec<&str> = expr
        .mods
        .iter()
        .chain(&key.implicit_mods)
        .map(|m| modifier_name(*m))
        .collect();
    let name = match key.page {
        UsagePage::Keyboard => keys::name(key.usage),
        UsagePage::Consumer if mods.is_empty() => keys::consumer(key.usage),
        _ => None,
    }
    .ok_or_else(|| format!("RMK has no key for `{}`", expr.key))?;
    Ok(if mods.is_empty() {
        name.to_string()
    } else {
        format!("WM({name}, {})", mods.join(" | "))
    })
}

fn layer_index(layer: LayerId, layers: &[LayerId]) -> Result<usize, String> {
    layers
        .iter()
        .position(|l| *l == layer)
        .ok_or_else(|| "the layer no longer exists".to_string())
}

/// The RMK key action for a binding. `layers` is the layout's layers in
/// order, and `ble_profiles` how many Bluetooth profiles the firmware
/// keeps. Fails, with the reason, for a binding RMK has nothing for.
pub fn action(binding: &Binding, layers: &[LayerId], ble_profiles: u8) -> Result<String, String> {
    let (label, params) = match binding {
        Binding::Raw { .. } => {
            return Err("devicetree text means nothing to RMK".into());
        }
        Binding::Behavior {
            behavior: BehaviorRef::BuiltIn(label),
            params,
        } => (label.as_str(), params.as_slice()),
        Binding::Behavior { .. } => {
            return Err("behaviors defined in the layout are not translated to RMK yet".into());
        }
    };
    let layer = |layer: &LayerId| layer_index(*layer, layers);
    // RMK's wireless keys are numbered after its profiles.
    let profiles = u32::from(ble_profiles);
    Ok(match (label, params) {
        ("trans", []) => "_".into(),
        ("none", []) => "No".into(),
        ("kp", [Param::Key(expr)]) => key_action(expr)?,
        ("mo", [Param::Layer(l)]) => format!("MO({})", layer(l)?),
        ("to", [Param::Layer(l)]) => format!("TO({})", layer(l)?),
        ("tog", [Param::Layer(l)]) => format!("TG({})", layer(l)?),
        ("sl", [Param::Layer(l)]) => format!("OSL({})", layer(l)?),
        ("sk", [Param::Key(expr)]) => match plain_key(expr) {
            Some(name)
                if name.ends_with("Ctrl")
                    || name.ends_with("Shift")
                    || name.ends_with("Alt")
                    || name.ends_with("Gui") =>
            {
                format!("OSM({name})")
            }
            _ => return Err("in RMK a sticky key can only be a single modifier".into()),
        },
        ("mt", [Param::Key(hold), Param::Key(tap)]) => {
            let hold = plain_key(hold).ok_or("in RMK a mod-tap holds a single modifier")?;
            format!("MT({}, {hold})", key_action(tap)?)
        }
        ("lt", [Param::Layer(l), Param::Key(tap)]) => {
            format!("LT({}, {})", layer(l)?, key_action(tap)?)
        }
        ("bootloader", []) => "Bootloader".into(),
        ("sys_reset", []) => "Reboot".into(),
        ("caps_word", []) => "CapsWordToggle".into(),
        ("key_repeat", []) => "Repeat".into(),
        ("mkp", [Param::Constant(button)]) => match button.as_str() {
            "LCLK" | "MB1" => "MouseBtn1".into(),
            "RCLK" | "MB2" => "MouseBtn2".into(),
            "MCLK" | "MB3" => "MouseBtn3".into(),
            "MB4" => "MouseBtn4".into(),
            "MB5" => "MouseBtn5".into(),
            other => return Err(format!("RMK has no mouse button for `{other}`")),
        },
        ("bt", [Param::Command { name, args }]) => match (name.as_str(), args.as_slice()) {
            ("BT_SEL", [profile]) if *profile < profiles => {
                format!("User{profile}")
            }
            ("BT_SEL", _) => {
                return Err(format!(
                    "this RMK firmware keeps {profiles} Bluetooth profiles"
                ));
            }
            ("BT_NXT", []) => format!("User{profiles}"),
            ("BT_PRV", []) => format!("User{}", profiles + 1),
            ("BT_CLR", []) => format!("User{}", profiles + 2),
            _ => return Err(format!("RMK has nothing for &bt {name}")),
        },
        ("out", [Param::Command { name, .. }]) if name == "OUT_TOG" => {
            format!("User{}", profiles + 3)
        }
        _ => return Err(format!("RMK has nothing for &{label}")),
    })
}

/// Whether a binding can be written as an RMK key action.
pub fn expressible(binding: &Binding, project: &Project, profile: &RmkProfile) -> bool {
    let layers: Vec<LayerId> = project.layers.iter().map(|l| l.id).collect();
    action(binding, &layers, profile.ble_profiles).is_ok()
}

/// What stops a layout from being built as RMK firmware.
pub fn check(project: &Project, profile: &RmkProfile) -> Vec<Problem> {
    let layers: Vec<LayerId> = project.layers.iter().map(|l| l.id).collect();
    let mut problems = Vec::new();
    let mut error = |location: Location, message: String| {
        problems.push(Problem {
            severity: Severity::Error,
            location,
            message,
        });
    };
    if profile.layers > 0 && project.layers.len() > profile.layers {
        error(
            Location::Project,
            format!(
                "the layout has {} layers, and this firmware holds {}",
                project.layers.len(),
                profile.layers
            ),
        );
    }
    for layer in &project.layers {
        for (position, binding) in layer.bindings.iter().enumerate() {
            if let Err(reason) = action(binding, &layers, profile.ble_profiles) {
                error(
                    Location::Key {
                        layer: layer.id,
                        position,
                    },
                    reason,
                );
            }
        }
    }
    for combo in &project.combos {
        if let Err(reason) = combo_entry(project, combo, &layers, profile) {
            error(Location::Combo(combo.id), reason);
        }
    }
    problems
}

/// One combo as an entry of RMK's combo list. RMK identifies a combo's
/// keys by what they do on the layer it applies to, not by position.
fn combo_entry(
    project: &Project,
    combo: &kc_model::features::Combo,
    layers: &[LayerId],
    profile: &RmkProfile,
) -> Result<String, String> {
    let on = match combo.layers.as_slice() {
        [] => None,
        [only] => Some(layer_index(*only, layers)?),
        _ => return Err("in RMK a combo applies to one layer or to all of them".into()),
    };
    let layer = &project.layers[on.unwrap_or(0)];
    let mut actions = Vec::new();
    for position in &combo.key_positions {
        let binding = layer
            .bindings
            .get(*position)
            .ok_or("the combo uses a key the layout does not have")?;
        let key = action(binding, layers, profile.ble_profiles)
            .map_err(|reason| format!("one of the combo's keys cannot be used in RMK: {reason}"))?;
        if key == "_" || key == "No" {
            return Err("in RMK a combo's keys must each do something on its layer".into());
        }
        actions.push(format!("\"{key}\""));
    }
    let output = action(&combo.binding, layers, profile.ble_profiles)?;
    let layer = on.map_or_else(String::new, |index| format!(", layer = {index}"));
    Ok(format!(
        "  {{ actions = [{}], output = \"{output}\"{layer} }},",
        actions.join(", ")
    ))
}

/// The keymap half of `keyboard.toml`: the layers, and the combos.
pub fn keymap(project: &Project, profile: &RmkProfile) -> Result<String, String> {
    let layers: Vec<LayerId> = project.layers.iter().map(|l| l.id).collect();
    let declared = project.layers.len().max(profile.layers);
    let mut out = format!("[keymap]\nlayers = {declared}\n");
    for layer in &project.layers {
        // The layer's name, kept out of anything RMK would have to parse.
        let name: String = layer
            .name
            .chars()
            .map(|c| if c.is_control() { ' ' } else { c })
            .collect();
        out.push_str(&format!("\n# {name}\n[[keymap.layer]]\nkeys = \"\"\"\n"));
        let mut actions = Vec::with_capacity(layer.bindings.len());
        for binding in &layer.bindings {
            actions.push(action(binding, &layers, profile.ble_profiles)?);
        }
        for row in actions.chunks(6) {
            out.push_str(&row.join("  "));
            out.push('\n');
        }
        out.push_str("\"\"\"\n");
    }
    // Layers the firmware counts on that the layout does not have let the
    // ones below show through.
    let keys = project.layers.first().map_or(0, |l| l.bindings.len());
    for number in project.layers.len()..declared {
        out.push_str(&format!(
            "\n# Unused layer {}\n[[keymap.layer]]\nkeys = \"\"\"\n",
            number + 1
        ));
        for row in vec!["_"; keys].chunks(6) {
            out.push_str(&row.join("  "));
            out.push('\n');
        }
        out.push_str("\"\"\"\n");
    }
    if !project.combos.is_empty() {
        let timeout = project
            .combos
            .iter()
            .filter_map(|c| c.timeout_ms)
            .max()
            .unwrap_or(50);
        out.push_str(&format!(
            "\n[behavior.combo]\ntimeout = \"{timeout}ms\"\ncombos = [\n"
        ));
        for combo in &project.combos {
            out.push_str(&combo_entry(project, combo, &layers, profile)?);
            out.push('\n');
        }
        out.push_str("]\n");
    }
    Ok(out)
}

fn side_name(side: Side) -> &'static str {
    match side {
        Side::Left => "left",
        Side::Right => "right",
    }
}

/// The name of the firmware file for one half, such as `imprint_left.uf2`.
pub fn artifact_name(profile: &FirmwareProfile, side: Side) -> String {
    format!("{}_{}.uf2", profile.config_name, side_name(side))
}

/// How a git revision is named in a Cargo dependency: a full commit hash
/// as `rev`, anything else as a tag.
fn cargo_pin(revision: &str) -> String {
    if revision.len() == 40 && revision.chars().all(|c| c.is_ascii_hexdigit()) {
        format!("rev = \"{revision}\"")
    } else {
        format!("tag = \"{revision}\"")
    }
}

const BUILD_RS: &str = r#"use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=keyboard.toml");
    println!("cargo:rerun-if-changed=memory.x");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("memory.x"))
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rustc-link-arg=--nmagic");
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rustc-link-arg=-Tdefmt.x");
}
"#;

/// Turns a raw firmware image into a UF2 file. Kept in the generated
/// repository so that the start address and family ID are this board's.
const UF2_PY: &str = r#"#!/usr/bin/env python3
"""Wraps a raw firmware image as a UF2 file: tools/uf2.py in.bin out.uf2 --base 0x26000 --family 0xADA52840"""
import argparse
import struct

parser = argparse.ArgumentParser()
parser.add_argument("source")
parser.add_argument("target")
parser.add_argument("--base", type=lambda v: int(v, 0), required=True)
parser.add_argument("--family", type=lambda v: int(v, 0), required=True)
args = parser.parse_args()

with open(args.source, "rb") as file:
    image = file.read()
chunks = [image[i : i + 256] for i in range(0, len(image), 256)]
with open(args.target, "wb") as file:
    for number, chunk in enumerate(chunks):
        header = struct.pack(
            "<IIIIIIII",
            0x0A324655,
            0x9E5D5157,
            0x00002000,  # the family ID is present
            args.base + number * 256,
            256,
            number,
            len(chunks),
            args.family,
        )
        file.write(header + chunk.ljust(476, b"\0") + struct.pack("<I", 0x0AB16F30))
print(f"{args.target}: {len(chunks)} blocks from {args.base:#x}, family {args.family:#x}")
"#;

/// The files of a firmware repository that builds RMK for `project`.
/// Paths are relative to the repository's root.
pub fn generate(
    project: &Project,
    board: &Board,
    profile: &FirmwareProfile,
) -> Result<Vec<(String, String)>, String> {
    let rmk = profile
        .rmk
        .as_ref()
        .ok_or("this firmware has no RMK build described")?;
    let keymap = keymap(project, rmk)?;
    let central = board
        .halves
        .iter()
        .find(|h| h.central)
        .ok_or("the board has no central half")?;
    let peripheral = board.halves.iter().find(|h| !h.central);
    let family = |half: &kc_boards::board::Half| half.uf2_family.unwrap_or(NRF52840_FAMILY);
    // Central first: which binary goes on which half, and its family.
    let mut images = vec![("central", central.side, family(central))];
    if let Some(half) = peripheral {
        images.push(("peripheral", half.side, family(half)));
    }
    let mut files: Vec<(String, String)> = Vec::new();
    let mut file = |path: &str, contents: String| files.push((path.to_string(), contents));

    match rmk.flavor {
        RmkFlavor::Upstream => {
            file(
                "keyboard.toml",
                format!("# {NOTICE}\n\n{}\n\n{keymap}", rmk.hardware.trim()),
            );
            file(
                "Cargo.toml",
                format!(
                    r#"# {NOTICE}
[package]
name = "{name}-rmk"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rmk = {{ git = "{url}", {pin}, default-features = false, features = ["defmt", "storage", "watchdog", "nrf52840_ble", "split", "async_matrix", "adafruit_bl"] }}
nrf-sdc = {{ version = "0.4.0", features = ["defmt", "peripheral", "central", "nrf52840"] }}
nrf-mpsl = {{ version = "0.4.0", features = ["defmt", "critical-section-impl", "nrf52840"] }}
bt-hci = {{ version = "0.10", features = ["defmt"] }}
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embassy-time = {{ version = "0.5", features = ["tick-hz-32_768", "defmt", "defmt-timestamp-uptime"] }}
embassy-nrf = {{ version = "0.11", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "nfc-pins-as-gpio", "time"] }}
embassy-executor = {{ version = "0.10", features = ["defmt", "platform-cortex-m", "executor-thread"] }}
defmt = "1"
defmt-rtt = "1"
panic-probe = {{ version = "1", features = ["print-defmt"] }}
static_cell = "2"

[[bin]]
name = "central"
path = "src/central.rs"

[[bin]]
name = "peripheral"
path = "src/peripheral.rs"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = "z"
overflow-checks = false
"#,
                    name = profile.config_name,
                    url = rmk.source.url,
                    pin = cargo_pin(&rmk.source.revision),
                ),
            );
            file(
                ".cargo/config.toml",
                format!(
                    "# {NOTICE}\n[build]\ntarget = \"thumbv7em-none-eabihf\"\n\n[env]\nDEFMT_LOG = \"off\"\nKEYBOARD_TOML_PATH = {{ value = \"keyboard.toml\", relative = true }}\n"
                ),
            );
            // The vendor's flash layout: the firmware starts where the
            // vendor's does and stops short of the vendor's settings.
            file(
                "memory.x",
                format!(
                    "/* {NOTICE} */\nMEMORY\n{{\n  FLASH : ORIGIN = {:#010x}, LENGTH = {:#010x}\n  RAM : ORIGIN = 0x20000008, LENGTH = 255K\n}}\n",
                    rmk.flash_origin, rmk.flash_length
                ),
            );
            file("build.rs", BUILD_RS.to_string());
            file(
                "src/central.rs",
                "#![no_main]\n#![no_std]\n\nuse rmk::macros::rmk_central;\n\n#[rmk_central]\nmod keyboard_central {}\n".into(),
            );
            file(
                "src/peripheral.rs",
                "#![no_main]\n#![no_std]\n\nuse rmk::macros::rmk_peripheral;\n\n#[rmk_peripheral(id = 0)]\nmod keyboard_peripheral {}\n".into(),
            );
            file("tools/uf2.py", UF2_PY.to_string());
            let mut convert = String::new();
            for (binary, side, family) in &images {
                convert.push_str(&format!(
                    "          \"$OBJCOPY\" -O binary target/thumbv7em-none-eabihf/release/{binary} {binary}.bin\n          python3 tools/uf2.py {binary}.bin {} --base {:#x} --family {family:#x}\n",
                    artifact_name(profile, *side),
                    rmk.flash_origin,
                ));
            }
            file(
                ".github/workflows/build.yml",
                format!(
                    r#"# {NOTICE}
name: Build RMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install the toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          rustup toolchain install stable --profile minimal --component llvm-tools
          rustup default stable
          rustup target add thumbv7em-none-eabihf
      - name: Build
        run: cargo build --release
      - name: Make the UF2 files
        run: |
          OBJCOPY="$(find "$(rustc --print sysroot)" -name llvm-objcopy | head -1)"
{convert}      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: "*.uf2"
"#
                ),
            );
        }
        RmkFlavor::MoergoRmk => {
            // That firmware has its own project for the board, with the
            // hardware, lighting and touchpads set up. Only the keymap is
            // ours: it is spliced over the one in its keyboard.toml.
            file("keymap.toml", format!("# {NOTICE}\n\n{keymap}"));
            file("tools/splice_keymap.py", SPLICE_PY.to_string());
            file(
                ".github/workflows/build.yml",
                format!(
                    r#"# {NOTICE}
name: Build RMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Fetch the firmware this keymap is built into
        run: |
          git clone {url} firmware
          git -C firmware checkout {revision}
          git -C firmware submodule update --init --recursive
      - name: Put this keymap into it
        run: python3 tools/splice_keymap.py keymap.toml firmware/{dir}/keyboard.toml
      - uses: cachix/install-nix-action@v25
      - name: Build
        run: cd firmware && nix develop --command just go60-firmware
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware/dist/**/*.uf2
"#,
                    url = rmk.source.url,
                    revision = rmk.source.revision,
                    dir = rmk.project_dir,
                ),
            );
        }
    }
    Ok(files)
}

/// Replaces the keymap in a firmware project's `keyboard.toml` with ours:
/// everything from `[keymap]` up to the next section that is not part of
/// the keymap or the combos.
const SPLICE_PY: &str = r#"#!/usr/bin/env python3
"""Replaces the keymap of a keyboard.toml: tools/splice_keymap.py keymap.toml keyboard.toml"""
import re
import sys

ours = open(sys.argv[1]).read()
target = open(sys.argv[2]).read()
ours_keymap = ours[ours.index("[keymap]") :]

# The combos, if we have any, replace theirs; otherwise theirs stay.
combo = re.search(r"^\[behavior\.combo\]\n.*?(?=^\[|\Z)", ours_keymap, re.S | re.M)
ours_layers = ours_keymap[: combo.start()] if combo else ours_keymap

start = target.index("[keymap]")
after = re.compile(r"^\[(?!keymap\]|\[keymap\.layer\]\])", re.M).search(target, start + 1)
end = after.start() if after else len(target)
target = target[:start] + ours_layers.rstrip() + "\n\n" + target[end:]

if combo:
    theirs = re.search(r"^\[behavior\.combo\]\n.*?(?=^\[|\Z)", target, re.S | re.M)
    if theirs:
        target = target[: theirs.start()] + combo.group(0) + target[theirs.end() :]
    else:
        target = target.rstrip() + "\n\n" + combo.group(0)

open(sys.argv[2], "w").write(target)
print(f"spliced {ours_layers.count('[[keymap.layer]]')} layers into {sys.argv[2]}")
"#;
